export { Engine, type RgbaColor, type View, type StrokeTarget, type FloatingState } from './engine'
export { DEFAULT_BRUSH, type BrushParams, type StrokePoint, type Dab } from './brush/types'
export { StrokeLayout } from './brush/stroke'
export { History, PixelPatch, type Command, type Rect } from './history/history'
export { type SelectionOp, type Point } from './selection/shapes'
export { extractKppPresetXml, parseKppParams, type KppParams } from './brush/kpp'
export { parseAbr, type AbrResult, type AbrTip } from './brush/abr'
export { runEngineSelfTest, type SelfTestResult } from './selftest'
export { measureTextBounds } from './text/rasterize'
